if(!require(devtools)) install.packages("devtools")
if(!require(magrittr)) install.packages("magrittr")
if(!require(rvest)) install.packages("rvest")
if(!require(readxl)) install.packages("readxl")
if(!require(maps)) install.packages("maps")
if(!require(reshape2)) install.packages("reshape2")
if(!require(ggiraph)) install.packages("ggiraph")
if(!require(RColorBrewer)) install.packages("RColorBrewer")
if(!require(leaflet)) install.packages("leaflet")
if(!require(rgdal)) install.packages("rgdal")
if(!require(shiny)) install.packages("shiny")
if(!require(shinyWidgets)) install.packages("shinyWidgets")
if(!require(shinythemes)) install.packages("shinythemes")
if(!require(DT)) install.packages("DT")
if(!require(plotly)) install.packages("plotly") # 1
if(!require(dplyr)) install.packages("dplyr") # 1
if(!require(shinydashboard)) install.packages("shinydashboard") # 1
if(!require(prophet)) devtools::install_github("facebook/prophet", subdir='R', ref="8306ae3")
if(!require(forecast)) install.packages("forecast")
if(!require(RcppArmadillo)) install.packages("RcppArmadillo")